# -*- coding: utf-8 -*-
"""Prediksi

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z08V6tj_o_U6lql_Yo-PPYRhRTeeueRi
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

url = "https://raw.githubusercontent.com/dicodingacademy/dicoding_dataset/main/employee/employee_data.csv"
data = pd.read_csv(url)

data['Attrition'].fillna(data['Attrition'].mode()[0], inplace=True)

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
categorical_cols = data.select_dtypes(include=['object']).columns
for col in categorical_cols:
    data[col] = le.fit_transform(data[col])

X = data.drop(columns=['Attrition'])
y = data['Attrition']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("\nAccuracy Score:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

cm = confusion_matrix(y_test, y_pred)
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Tidak Attrition', 'Attrition'],
            yticklabels=['Tidak Attrition', 'Attrition'])
plt.title('Matriks Konfusi untuk Prediksi Attrition')
plt.xlabel('Prediksi')
plt.ylabel('Aktual')
plt.show()